name: shared
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.22.0'

dependency_overrides:
  analyzer: 6.4.1 #6.7.0

dependencies:
  android_id: 0.4.0
  async: 2.11.0
  dartx: 1.2.0
  decimal: 3.0.2
  device_info_plus: 10.1.0
  flutter:
    sdk: flutter
  flutter_cache_manager: 3.3.2
  flutter_udid: 3.0.0
  injectable: 2.4.2
  intl: 0.19.0
  mime: 1.0.5
  package_info_plus: 8.0.0
  path_provider: 2.1.3
  rxdart: 0.27.7 #0.28.0
  timezone: 0.9.3
  url_launcher: 6.3.0

dev_dependencies:
  build_runner: 2.4.11
  custom_lint: 0.6.4
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.5.2 #2.5.3
  freezed_annotation: 2.4.1
  injectable_generator: 2.6.1
  logging: 1.2.0
  mocktail: 1.0.4
  nals_lints:
    path: ../nals_lints
