name: resources
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.22.0'

dependency_overrides:
  analyzer: 6.4.1 #6.7.0
  
dependencies:
  flutter:
    sdk: flutter
  flutter_gen: any

dev_dependencies:
  # flutter_lints: 1.0.4
  flutter_test:
    sdk: flutter
  intl: 0.19.0
  intl_utils: 2.8.7

flutter_intl:
  enabled: true
  main_locale: en
  output_dir: lib/src/generated
  arb_dir: lib/src/l10n