name: office_reader
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.22.0'
dependency_overrides:
  analyzer: 6.4.1 #6.7.0
  js: ^0.7.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  async: 2.11.0
  auto_route: 8.2.0
  cached_network_image: 3.3.1
  cupertino_icons: 1.0.8
  dartx: 1.2.0
  flutter_bloc: 8.1.6
  flutter_local_notifications: 17.2.1+1
  flutter_screenutil: 5.9.3
  flutter_svg: 2.0.10+1
  get_it: 7.7.0
  infinite_scroll_pagination: 4.0.0
  injectable: 2.4.2
  rxdart: 0.27.7 #0.28.0
  tuple: 2.0.2
  initializer:
    path: ../packages/initializer
  shared:
    path: ../packages/shared
  resources:
    path: ../packages/resources
  domain:
    path: ../packages/domain

dev_dependencies:
  auto_route_generator: 8.0.0
  bloc_test: 9.1.7
  build_runner: 2.4.11
  custom_lint: 0.6.4
  flutter_gen_runner: 5.6.0
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  flutter_native_splash: 2.4.0
  flutter_test:
    sdk: flutter
  freezed: 2.5.2 #2.5.3
  freezed_annotation: 2.4.1
  injectable_generator: 2.6.1
  logging: 1.2.0
  mocktail: 1.0.4
  nals_lints:
    path: ../packages/nals_lints

# Config generate when build
flutter_gen:
  output: lib/resource/generated
  line_lenght: 180
  null_safety: true

  integrations:
    flutter_svg: true
    # flare_flutter: true

  assets:
    enabled: true

  fonts:
    enabled: true
  # colors:
  #   enabled: true
  #   inputs:
  #     - assets/color/colors.xml
flutter:
  uses-material-design: true
  generate: false
  assets:
    - assets/images/
#  fonts:
#    - family: Muli
#      fonts:
#        - asset: assets/fonts/Muli-Bold.ttf
#          weight: 900
#        - asset: assets/fonts/Muli-SemiBold.ttf
#          weight: 700
#        - asset: assets/fonts/Muli-Regular.ttf
#          weight: 400
