name: nals_lints
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.22.0'

dependency_overrides:
  analyzer: 6.4.1 #6.7.0

dependencies:
  custom_lint_builder: 0.6.4
  source_gen: 1.5.0
